// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tuaavguqfgmeazqwgtcf.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YWF2Z3VxZmdtZWF6cXdndGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI1ODQ5MDIsImV4cCI6MjA0ODE2MDkwMn0._vbvM0jKowTwDczuerdYXPHcDZVdti5OE5dgS7TTKog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);